name: lambda_deploy
on: [push]
jobs: 
  lambda_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
      - name: create_deployment_zip
        run: |
          sudo apt install zip
          mkdir -p ./deployment_zip 
          pip install snowflake-connector-python --platform manylinux2010_x86_64 --only-binary=:all: -t ./deployment_zip
          cp ./src/lambda_function.py  ./deployment_zip
          cd deployment_zip 
          zip -r lambda_zip.zip *
      - name: lambda_code_update
        run: |
          aws lambda update-function-code --function-name compost-chatbot --zip-file fileb://./deployment_zip/lambda_zip.zip

# TODO: replace "lambda_deployment_via_gitaction" with the actual name of Lambda function.